apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: rc2
  name: registry-alb        
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: registry-group
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
    ingress.kubernetes.io/rewrite-target: /   # Added rewrite annotation here for / to /selfservice
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:370803901956:certificate/59fa4298-f8da-4d53-9314-8b7266416460
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-registry-cred
                port:
                  number: 8081
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: demo-registry-cred-keycloak-service
                port:
                  number: 8080


