apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: registry-alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
    alb.ingress.kubernetes.io/target-type: ip
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/group.name":"registry-alb","alb.ingress.kubernetes.io/listen-ports":"[{\"HTTP\": 80}]","alb.ingress.kubernetes.io/scheme":"internet-facing","alb.ingress.kubernetes.io/target-group-attributes":"stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600","alb.ingress.kubernetes.io/target-type":"ip","kubernetes.io/ingress.class":"alb","meta.helm.sh/release-name":"demo-registry-cred","meta.helm.sh/release-namespace":"rc2"},"creationTimestamp":"2024-04-02T13:15:56Z","finalizers":["group.ingress.k8s.aws/registry-alb"],"generation":1,"labels":{"app.kubernetes.io/instance":"demo-registry-cred","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"keycloak-service","app.kubernetes.io/version":"latest","helm.sh/chart":"keycloak-service-0.0.1"},"name":"demo-registry-cred-keycloak-service","namespace":"rc2","resourceVersion":"4872140","uid":"fe2dd517-7970-4904-89b8-934fa5ed2cf4"},"spec":{"ingressClassName":"alb","rules":[{"host":"registry.demodpgs.net","http":{"paths":[{"backend":{"service":{"name":"demo-registry-cred-keycloak-service","port":{"number":8080}}},"path":"/auth","pathType":"Prefix"},{"backend":{"service":{"name":"vault","port":{"number":8200}}},"path":"/*","pathType":"Prefix"}]}}]},"status":{"loadBalancer":{"ingress":[{"hostname":"k8s-registryalb-25f11ad17a-277111958.ap-south-1.elb.amazonaws.com"}]}}}
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: demo-registry-cred
    meta.helm.sh/release-namespace: rc2
  creationTimestamp: "2024-04-02T13:15:56Z"
  finalizers:
  - group.ingress.k8s.aws/registry-alb
  generation: 2
  labels:
    app.kubernetes.io/instance: demo-registry-cred
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak-service
    app.kubernetes.io/version: latest
    helm.sh/chart: keycloak-service-0.0.1
  name: demo-registry-cred-keycloak-service
  namespace: rc2
  resourceVersion: "4884095"
  uid: fe2dd517-7970-4904-89b8-934fa5ed2cf4
spec:
  ingressClassName: alb
  rules:
  - host: registry.demodpgs.net
    http:
      paths:
      - backend:
          service:
            name: demo-registry-cred-keycloak-service
            port:
              number: 8080
        path: /auth
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: k8s-registryalb-25f11ad17a-277111958.ap-south-1.elb.amazonaws.com
