global:
  host: "registry.demodpgs.net"
  database:
    host: "rdsstack-databaseb269d8bb-wtjrn0lxj2sw.cluster-cveklit2rj4m.ap-south-1.rds.amazonaws.com"
    user: "postgres"
    port: "5432"
    vendor: "postgres"
  keycloak:
    database: "registryrc"
    admin:
      username: "admin"
    proxy_forwarding: true
  registry:
    database: "registryrc"
    search_provider: "dev.sunbirdrc.registry.service.NativeSearchService"
    signature_provider: "dev.sunbirdrc.registry.service.impl.SignatureV2ServiceImpl"
    sso:
      realm: "sunbird-rc"
      admin_client_id: "admin-api"
      client_id: "registry-frontend"
    signature_enabled: true
    keycloak_user_set_password: false
    base_apis_enabled: false
    log_level: DEBUG
    enable_external_templates: true
    enable_async: false
    enable_authentication: true
    enable_webhook: false
    webhook_url: http://localhost:5001/api/v1/callback
    manager_type: DefinitionsManager
    swagger_enabled: true
    swagger_title: SUNBIRD-RC
    authentication_enabled: true
    claims_enabled: true
    certificate_enabled: true
    encryption_enabled: false
    idgen_enabled: false
    opa_enabled: false
    opa_allow_key_name: authorized
    encryption_port : 8013
    context_path : /
    idformatFromMdms: false
    mdmsProvider: org.egov.id.masterdata.provider.DBMasterDataProvider
    autoCreateNewSeq: true
    migrationEnabled: true
    did_enabled: true
    credential_did_method: rcw
    issuer_did_method : issuer
    schema_author: Registry
    schema_author_did_method: author
    envVars:
      egov_mdms_provider: org.egov.id.masterdata.provider.DBMasterDataProvider
  minio:
    url:
    access_key: admin
    bucket_key: sunbird-rc
  elastic_search:
    url:
    auth_enabled: false
    username: ""
  kafka:
    url:
  redis:
    host:
    port: 6379
  vault:
    address: http://vaultkv:8200
    base_url: http://vaultkv:8200/v1
    root_path: http://vaultkv:8200/v1/kv
    vault_timeout: 5000
    vault_proxy: false
    vault_token: <VAULT_ROOT_TOKEN> 
  sunbird:
    enable_auth: false
    signing_algo: Ed25519
    jwks_uri: ""
  secrets:
    DB_PASSWORD: aXBkQWleay0tPUhtTW5ZQmtUeFZJVmVyLTQxdGFq
    ELASTIC_SEARCH_PASSWORD: ""
    KEYCLOAK_ADMIN_CLIENT_SECRET: YjJiMGNhYjEtMjQzZC00ZTZlLTkzZTctOTAxNWZmNjZkZjJi
    KEYCLOAK_ADMIN_PASSWORD: YWRtaW4xMjM=
    KEYCLOAK_DEFAULT_USER_PASSWORD: YWRtaW5AMTIz
    MINIO_SECRET_KEY: Kgo=
    VAULT_SECRET_TOKEN: aHZzLkVOSDBYTGI1WGFqc056bWJPNGJiWmtIYg==
    DB_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczppcGRBaV5rLS09SG1NbllCa1R4VklWZXItNDF0YWpAcmRzc3RhY2stZGF0YWJhc2ViMjY5ZDhiYi13dGpybjBseGoyc3cuY2x1c3Rlci1jdmVrbGl0MnJqNG0uYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3N1bmJpcmRyY2NyZWQ=
encryption-service:
  envVars:
    egov_mdms_provider: org.egov.enc.masterdata.provider.DBMasterDataProvider
id-gen-service:
  envVars:
    egov_mdms_provider: org.egov.id.masterdata.provider.DBMasterDataProvider
